name: Go CI/CD

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_GMAIL_PASSWORD: ${{ secrets.GOOGLE_GMAIL_PASSWORD }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
      TEXTBELT_API_KEY: ${{ secrets.TEXTBELT_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24' # Or your desired version
          
      - name: Build
        run: go build
        
      - name: Test
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic
        
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.txt
